# Utilise l'image officielle MongoDB
FROM mongo:7.0

# Crée un répertoire pour stocker les fichiers de sauvegarde
RUN mkdir -p /backup

# Copie la sauvegarde locale vers le conteneur
COPY backup /backup

# Restaurer la base de données à partir de la sauvegarde
CMD ["mongorestore", "--drop", "--dir", "/backup"]
